# Generated by Django 3.1.7 on 2021-03-08 15:29

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='manager_description',
            field=models.TextField(default='Manager description'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='menu_list',
            field=models.JSONField(default=backend.models.Fridge.menu_list_default),
        ),
        migrations.AddField(
            model_name='fridge',
            name='my_maps_description',
            field=models.TextField(default='My Maps description'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fridge')),
            ],
        ),
    ]
