# Generated by Django 3.1.7 on 2021-03-09 14:22

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210308_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='backend.fridge'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=backend.models.user_directory_path),
        ),
    ]
