# Generated by Django 3.1.7 on 2021-03-17 15:46

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_fridge_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='menu_list',
            field=models.JSONField(blank=True, default=backend.models.Fridge.menu_list_default),
        ),
    ]
