# Generated by Django 3.1.7 on 2021-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
