# Generated by Django 3.1.7 on 2021-03-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_favorite_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='isActive',
        ),
    ]
