# Generated by Django 3.1.7 on 2021-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmlFile', models.FileField(upload_to='kml/%Y/%m/%d/')),
            ],
        ),
    ]
