# Generated by Django 3.1.7 on 2021-04-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210405_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmlfile',
            name='geojson_file',
            field=models.FileField(default='', upload_to='kml/%Y/%m/%d/'),
        ),
    ]
