# Generated by Django 3.1.7 on 2021-04-14 09:33

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_kmlfile_geojson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='image', unique=True),
        ),
    ]
